# Generated by Django 2.2.7 on 2021-01-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.IntegerField(default=0, null=True)),
                ('company_name', models.CharField(default='', max_length=30, null=True)),
                ('reviewCount', models.IntegerField(default=0)),
                ('average', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('wlb', models.IntegerField(default=0)),
                ('culture', models.IntegerField(default=0)),
                ('possibility', models.IntegerField(default=0)),
                ('management', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='jobdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('python', models.IntegerField(default=0)),
                ('java', models.IntegerField(default=0)),
                ('javascript', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='recruit_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=30)),
                ('titleId', models.IntegerField(default=0)),
                ('job', models.CharField(max_length=30)),
                ('skill', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('require', models.CharField(max_length=50)),
                ('prefer', models.CharField(max_length=50)),
                ('jobUrl', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillId', models.IntegerField(default=0)),
                ('skill', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleId', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
    ]
