# Generated by Django 3.1.5 on 2021-01-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('companyId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=30, null=True)),
                ('reviewCount', models.IntegerField(default=0)),
                ('average', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('wlb', models.IntegerField(default=0)),
                ('culture', models.IntegerField(default=0)),
                ('possibility', models.IntegerField(default=0)),
                ('management', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='jobdict',
            fields=[
                ('job', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('skill', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recruit_info',
            fields=[
                ('titleId', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=100)),
                ('require', models.CharField(max_length=100)),
                ('prefer', models.CharField(max_length=100)),
                ('jobUrl', models.CharField(max_length=100)),
                ('total_skill', models.CharField(max_length=200)),
                ('total_skill_literal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('needSkill', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('web', models.IntegerField(default=0)),
                ('network', models.IntegerField(default=0)),
                ('se', models.IntegerField(default=0)),
                ('soft', models.IntegerField(default=0)),
                ('qa', models.IntegerField(default=0)),
                ('plan', models.IntegerField(default=0)),
                ('da', models.IntegerField(default=0)),
                ('app', models.IntegerField(default=0)),
                ('pm', models.IntegerField(default=0)),
                ('game', models.IntegerField(default=0)),
                ('dba', models.IntegerField(default=0)),
                ('consulting', models.IntegerField(default=0)),
                ('he', models.IntegerField(default=0)),
                ('cd', models.IntegerField(default=0)),
                ('gd', models.IntegerField(default=0)),
                ('ad', models.IntegerField(default=0)),
                ('marketing', models.IntegerField(default=0)),
                ('market', models.IntegerField(default=0)),
                ('sa', models.IntegerField(default=0)),
                ('wp', models.IntegerField(default=0)),
                ('ud', models.IntegerField(default=0)),
                ('md', models.IntegerField(default=0)),
                ('strategy', models.IntegerField(default=0)),
                ('advertise', models.IntegerField(default=0)),
                ('video', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('support', models.IntegerField(default=0)),
                ('erp', models.IntegerField(default=0)),
                ('iu', models.IntegerField(default=0)),
                ('wd', models.IntegerField(default=0)),
                ('machine', models.IntegerField(default=0)),
                ('esemi', models.IntegerField(default=0)),
                ('control', models.IntegerField(default=0)),
                ('elec', models.IntegerField(default=0)),
                ('dsemi', models.IntegerField(default=0)),
                ('econtrol', models.IntegerField(default=0)),
                ('domsales', models.IntegerField(default=0)),
                ('sound', models.IntegerField(default=0)),
                ('itsol', models.IntegerField(default=0)),
                ('emarketing', models.IntegerField(default=0)),
                ('smarketing', models.IntegerField(default=0)),
                ('bd', models.IntegerField(default=0)),
                ('bmarketing', models.IntegerField(default=0)),
                ('publish', models.IntegerField(default=0)),
                ('pd', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('culture', models.IntegerField(default=0)),
                ('crm', models.IntegerField(default=0)),
                ('maintenance', models.IntegerField(default=0)),
                ('tech', models.IntegerField(default=0)),
                ('product', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleId', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
    ]
